{
 "title": "Custom Exporter для OpenWeather API",
 "time": { "from": "2025-11-07T13:38:40.827Z", "to": "2025-11-07T13:48:49.496Z" },
 "panels": [
  {
   "title": "Visibility (km)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_visibility_meters / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cloudiness (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_cloudiness_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed (m/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_wind_speed_mps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Latency (s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_pressure_hpa", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time Since Last Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "time() - weather_last_update_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "deriv(weather_temperature_celsius[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Temperature (5m)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}